### ISSUE TITLE
Omitted files during export (Ref: Rating on Addon Page)

### ISSUE THREAD

**Issue by anphex** [tmccoid-tech/extract-em#17] opened 2024-07-24 10:40 UTC
Greetings, 

I
![image](https://github.com/user-attachments/assets/9274f0ef-b15e-4fea-b987-b66a6569bb76)

I checked your suggestion about duplicates but I couldn't find any explizit mention of duplicates. The extract in this example processed 137 mails that clearly have each a single PDF attached. In this folder there are payment notices, invoices and invoice listings. The invoices arent found at all as it turns out. 

Due to GDPR I can't attach a file but the name pattern of the invoices is still 

"RG_880_240010_1527506.pdf"

It's also noteworthy that these PDF are in the German Invoice fomart ZugFERD, but it's still a normal PDF with some XML inside.

**Comment by tmccoid-tech** [comment] 2024-07-24 15:55
Hi Anphex,

When using the Let Me Choose method, you will not immediately see a reference to duplicates.  When you click the Extract 'Em button after discovery is complete, a duplicate count is displayed on the second line of the Exclusions section highlighted in red.

https://tmccoid.tech/images/extractem/screenshots/EE-03_03%20Extract%20Immediate.png

Once extraction is complete, provided that you have the most recent version of Extract 'Em! installed (1.3.1), you can generate an extraction report which will tell you exactly which attachments in which emails were identified as duplicates.  Please review this file.  An attachment is considered a duplicate if it has precisely the same name and file size down to the byte.

If you are still finding that non-duplicate attachments are being incorrectly omitted, please attach to this bug report the extraction report and, if the data is not especially sensitive, one of the emails containing an omitted attachment.  If the email file is too sensitive for the public but you are comfortable with me reviewing it, rather than attaching it here you can email it to me at extractem-dev@tmccoid.tech; please save the email file locally rather than forwarding it, and change the file extension from .eml to .txt before you attach it.

Thanks for your assistance,
Tom

**Comment by tmccoid-tech** [comment] 2024-08-08 23:58
I am closing this issue -- the problem was due to the Thunderbird API, not the extension itself, and the underlying issue has been resolved as of the release of TB 128.

**Closed by tmccoid-tech** 2024-08-08 23:58 UTC

**Comment by afilp** [comment] 2024-09-08 20:03
@tmccoid-tech Almost half of my extracted images show as duplicates (they are camera screen captures) but I am not sure that they are really duplicates (as the byte size may not be the proper way to identify them).

It would be really helpful in order to detect if this is a false positive if we could have the date AND TIME of the given email here, so that I can detect the 2 emails that seem to have duplicate images:

![image](https://github.com/user-attachments/assets/d6ba0b22-e6ee-4fad-8175-031b6a23b1a8)

Is this possible please?

**Comment by afilp** [comment] 2024-09-08 20:17
Another problem, where this statement seems to not be working:
"An attachment is considered a duplicate if it has precisely the same name and file size down to the byte."

RESULT IN **DUPLICATES**:
![image](https://github.com/user-attachments/assets/fcc45467-4e8f-4c75-a550-ebbfeb6153cd)

ALL **NON-DUPLICATES** ACTUALLY EXPORTED WITH SAME SIZE (239.4 KB):
![image](https://github.com/user-attachments/assets/ec6e1801-5e85-462e-b46e-1e1ee50b44f5)

As we can see, none of the file names of non-duplicates at 239.4KB have the name "D01-0.jpg".

So why did the "D01-0.jpg" was considered a duplicate?
(we do have other files as "D01-0.jpg" but not at the same file size).

Thank you!

**Comment by afilp** [comment] 2024-09-08 20:22
I have the impression that the same file names are just ommitted (only the 1st is exported), regardless of the file size. I did a smple search and found this (but not sure, it was just a sample).

**Comment by tmccoid-tech** [comment] 2024-09-08 20:40
Hi,

Regarding the first issue/request, I can add that with no problem.  With any luck that will be generally available sometime next week.  I can also send you a preview version of the extension if you would like, with instructions on how to side-load it.

As far as the second issue is concerned, 239.4 kb does not necessarily equal 239. 4 kb; the value is rounded and may therefore (roughly) be anywhere between 239.350 kb and 239.499 kb.  However, adding the size in raw bytes on the report would help in identifying if this is an actual as opposed to apparent problem.

You are correct that name + byte size is not ideal, a checksum value would be preferable, but this requires loading each attachment in advance which would reduce performance.

I do not believe you are correct about your most recent impression, but I will check into this as well.  I may ask for a couple of sample files to try to reproduce the issue.

**Comment by afilp** [comment] 2024-09-08 20:47
"However, adding the size in raw bytes on the report would help in identifying if this is an actual as opposed to apparent problem."

Excellent! Thanks!

**Comment by afilp** [comment] 2024-09-08 20:49
"I do not believe you are correct..."

Indeed! I made more tests and I found this:

![image](https://github.com/user-attachments/assets/8c1764e0-d561-4f5e-904f-a9f5f87fa17a)

So, your code works as expected!

However, this is not enough... Since all attachments are 1-year emails from security cameras, the image names are the same. So I have many "false duplicates" because some file sizes are the same (while the names are the same), despite they are totally different images.

**Comment by afilp** [comment] 2024-09-08 20:56
"but this requires loading each attachment in advance which would reduce performance."

Indeed, but maybe we can have this option:  

**"[ ] Compare with checksums (takes longer) when detecting duplicates"**

And you do not need to do this for all files, just when you find a "name-bytesize" equality, only then, you take the extra step of comparing the checksums of these 2 images (and keep their checksum info on memory if they need to be re-compared with another image on next emails).

**Comment by afilp** [comment] 2024-09-08 21:04
Finally, it would be REALLY helpful if we could have this option:

**[ ] Append the modified date/time to filenames**

Why?

See what result I get here, due the security camera emails using the same name:

![image](https://github.com/user-attachments/assets/92f40238-676d-4a48-8a1e-d0bc9fedbc36)

As you can see the attached image always had the name "Camera1-1.jpg", so when extracting and unzipping I just get a serial number next to the filenames.

It would be great if i had the option to append the modified date AND time (you find it on the last column) to the filename, much more useful.

If you agree, it should be on this notation which will help us sort the files by date:

YYYY-MM-DD-HHMM

Example:
2024-08-22-2356

So, output filename examples:
Camera1-1-2024-08-22-2356.jpg
Camera1-1-2024-08-27-0914.jpg
..etc.

**Comment by tmccoid-tech** [comment] 2024-09-08 21:14
Currently you can append the date using the filename pattern option.  The time element is not available at this time, though.

**Comment by afilp** [comment] 2024-09-08 21:40
Nice! The "time" option would be great also, as we have many images of the camera on the same date (even the seconds could matter...!)

**Comment by tmccoid-tech** [comment] 2024-09-10 18:10
@ afilp: I have opened a separate Github issue to manage this; please refer to the following going forward:

[Revised duplicate identification/omission logic](https://github.com/tmccoid-tech/extract-em/issues/22)

**Comment by tmccoid-tech** [comment] 2024-09-18 19:13
@ afilp: Please see [Revised duplicate identification/omission logic](https://github.com/tmccoid-tech/extract-em/issues/22) for an update on this.
